-- SQL de Inicialización de Base de Datos para Nutri-Fit
-- Este script define la estructura lógica del proyecto, separando responsabilidades en tres esquemas principales.
-- Corresponde a la especificación detallada en docs/db/diseno_db.md.

BEGIN;

-- Crear esquemas del proyecto
CREATE SCHEMA IF NOT EXISTS nutrition;
CREATE SCHEMA IF NOT EXISTS training;

-- ============================================================================
-- 2. TABLAS EN EL ESQUEMA 'public' (Núcleo y Usuarios)
-- ============================================================================

-- Tabla para almacenar los perfiles físicos e información básica del usuario
CREATE TABLE IF NOT EXISTS public.users (
    id UUID,
    name TEXT NOT NULL,
    birth_date DATE NOT NULL,
    gender TEXT NOT NULL,
    height_cm REAL NOT NULL,
    body_type TEXT,
    pal_level REAL DEFAULT 1.2 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT chk_users_gender CHECK (gender IN ('M', 'F')),
    CONSTRAINT chk_users_body_type CHECK (body_type IN ('ectomorph', 'mesomorph', 'endomorph'))
);

-- Comentarios informativos sobre la tabla de usuarios
COMMENT ON TABLE public.users IS 'Almacena la información del perfil físico de los usuarios vinculados a Supabase Auth.';
COMMENT ON COLUMN public.users.id IS 'Referencia directa al ID de usuario de Supabase Auth.';

-- ============================================================================
-- 3. TABLAS EN EL ESQUEMA 'nutrition' (Módulo de Alimentación)
-- ============================================================================

-- Tabla para definir los objetivos nutricionales diarios del usuario
CREATE TABLE IF NOT EXISTS nutrition.user_goals (
    user_id UUID,
    target_calories INTEGER NOT NULL,
    target_protein_g REAL NOT NULL,
    target_carbs_g REAL NOT NULL,
    target_fat_g REAL NOT NULL,
    goal_type TEXT,
    CONSTRAINT pk_user_goals PRIMARY KEY (user_id),
    CONSTRAINT fk_user_goals_users FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT chk_user_goals_goal_type CHECK (goal_type IN ('deficit', 'maintenance', 'surplus'))
);

COMMENT ON TABLE nutrition.user_goals IS 'Establece los objetivos calóricos y macronutrientes del usuario según su tipo de meta física.';

-- Tabla para el registro de comidas consumidas por el usuario
CREATE TABLE IF NOT EXISTS nutrition.food_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id UUID NOT NULL,
    logged_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    meal_type TEXT NOT NULL,
    food_name TEXT NOT NULL,
    calories REAL NOT NULL,
    protein_g REAL NOT NULL,
    carbs_g REAL NOT NULL,
    fat_g REAL NOT NULL,
    serving_size_g REAL NOT NULL,
    CONSTRAINT pk_food_logs PRIMARY KEY (id),
    CONSTRAINT fk_food_logs_users FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE,
    CONSTRAINT chk_food_logs_meal_type CHECK (meal_type IN ('breakfast', 'lunch', 'dinner', 'snack'))
);

COMMENT ON TABLE nutrition.food_logs IS 'Mantiene el historial diario de alimentos consumidos por el usuario.';

-- Tabla para almacenar la caché de alimentos buscados por código de barras (OpenFoodFacts)
CREATE TABLE IF NOT EXISTS nutrition.food_cache (
    barcode TEXT NOT NULL,
    food_name TEXT NOT NULL,
    calories REAL NOT NULL,
    protein_g REAL NOT NULL,
    carbs_g REAL NOT NULL,
    fat_g REAL NOT NULL,
    serving_size_g REAL NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    CONSTRAINT pk_food_cache PRIMARY KEY (barcode)
);

COMMENT ON TABLE nutrition.food_cache IS 'Almacena temporalmente o como caché los alimentos consultados exitosamente por código de barras.';

-- ============================================================================
-- 4. TABLAS EN EL ESQUEMA 'training' (Módulo de Entrenamiento)
-- ============================================================================

-- Tabla de catálogo de ejercicios disponibles
CREATE TABLE IF NOT EXISTS training.exercises (
    id INTEGER,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    equipment TEXT,
    CONSTRAINT pk_exercises PRIMARY KEY (id)
);

COMMENT ON TABLE training.exercises IS 'Catálogo estático de ejercicios disponibles para las rutinas.';

-- Tabla para las sesiones de entrenamiento de los usuarios
CREATE TABLE IF NOT EXISTS training.workout_sessions (
    id UUID DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    started_at TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ,
    name TEXT NOT NULL,
    CONSTRAINT pk_workout_sessions PRIMARY KEY (id),
    CONSTRAINT fk_workout_sessions_users FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE
);

COMMENT ON TABLE training.workout_sessions IS 'Registra las sesiones individuales de entrenamiento iniciadas y finalizadas.';

-- Tabla para las series (sets) ejecutadas de cada ejercicio en una sesión
CREATE TABLE IF NOT EXISTS training.workout_sets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    session_id UUID NOT NULL,
    exercise_id INTEGER NOT NULL,
    set_number INTEGER NOT NULL,
    weight REAL NOT NULL,
    reps INTEGER NOT NULL,
    rpe REAL,
    completed BOOLEAN DEFAULT TRUE NOT NULL,
    CONSTRAINT pk_workout_sets PRIMARY KEY (id),
    CONSTRAINT fk_workout_sets_sessions FOREIGN KEY (session_id) REFERENCES training.workout_sessions(id) ON DELETE CASCADE,
    CONSTRAINT fk_workout_sets_exercises FOREIGN KEY (exercise_id) REFERENCES training.exercises(id) ON DELETE RESTRICT
);

COMMENT ON TABLE training.workout_sets IS 'Detalla cada serie completada dentro de una sesión de entrenamiento.';

-- ============================================================================
-- 5. PERMISOS PARA EL ROL 'anon' (PostgREST)
-- ============================================================================

GRANT USAGE ON SCHEMA nutrition TO anon;
GRANT USAGE ON SCHEMA training TO anon;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon;
GRANT ALL ON ALL TABLES IN SCHEMA nutrition TO anon;
GRANT ALL ON ALL TABLES IN SCHEMA training TO anon;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA nutrition TO anon;
GRANT USAGE ON ALL SEQUENCES IN SCHEMA training TO anon;

COMMIT;
