-- Fase F17 (Cardio + Búsqueda de Comida) — T17.1.2
-- Corre DESPUÉS de zzzz4_cardio_and_weight.sql por orden alfabético en
-- docker-entrypoint-initdb.d. Catálogo curado y PÚBLICO de platos peruanos:
-- mismo patrón que training.exercises (catálogo sin dueño, GRANT SELECT a anon).
-- OJO: z_init.sql hace GRANT ALL ... TO anon sobre las tablas existentes en ese
-- momento; food_catalog aún no existe entonces, por eso el GRANT explícito aquí.

BEGIN;

CREATE TABLE IF NOT EXISTS nutrition.food_catalog (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT,
    calories REAL NOT NULL,
    protein_g REAL NOT NULL,
    carbs_g REAL NOT NULL,
    fat_g REAL NOT NULL,
    serving_size_g REAL NOT NULL
);

COMMENT ON TABLE nutrition.food_catalog IS 'Catálogo curado de platos peruanos comunes (F17). Macros son ESTIMACIONES aproximadas por porción típica, no valores de laboratorio.';

-- Lectura pública, mismo patrón que training.exercises (catálogo sin dueño).
GRANT SELECT ON nutrition.food_catalog TO anon, authenticated;

INSERT INTO nutrition.food_catalog (name, category, calories, protein_g, carbs_g, fat_g, serving_size_g) VALUES
  ('Arroz con Pollo', 'plato de fondo', 550, 28, 65, 18, 350),
  ('Ceviche de Pescado', 'entrada', 250, 30, 18, 6, 250),
  ('Lomo Saltado', 'plato de fondo', 620, 32, 55, 28, 350),
  ('Pollo a la Brasa (1/4)', 'plato de fondo', 500, 40, 20, 28, 300),
  ('Ají de Gallina', 'plato de fondo', 480, 26, 40, 24, 300),
  ('Causa Rellena', 'entrada', 320, 10, 45, 12, 250),
  ('Papa a la Huancaína', 'entrada', 300, 8, 35, 15, 200),
  ('Anticuchos de Corazón', 'entrada', 280, 26, 12, 14, 200),
  ('Tacu Tacu con Bistec', 'plato de fondo', 700, 30, 75, 30, 400),
  ('Seco de Res con Frejoles', 'plato de fondo', 650, 35, 60, 25, 400),
  ('Cau Cau de Mondongo', 'plato de fondo', 420, 22, 45, 16, 350),
  ('Rocoto Relleno', 'plato de fondo', 380, 18, 25, 22, 250),
  ('Chicharrón de Chancho', 'plato de fondo', 550, 32, 15, 40, 250),
  ('Tallarín Saltado', 'plato de fondo', 600, 26, 65, 24, 350),
  ('Arroz Chaufa de Pollo', 'plato de fondo', 580, 24, 70, 22, 350),
  ('Sopa a la Minuta', 'sopa', 350, 18, 35, 14, 400),
  ('Aguadito de Pollo', 'sopa', 380, 22, 40, 12, 400),
  ('Chupe de Camarones', 'sopa', 450, 24, 35, 22, 400),
  ('Tamal Peruano', 'entrada', 320, 10, 40, 14, 200),
  ('Humita', 'entrada', 250, 6, 35, 10, 180),
  ('Salchipapa', 'plato de fondo', 650, 18, 65, 38, 350),
  ('Pan con Chicharrón', 'sandwich', 480, 20, 45, 25, 220),
  ('Turrón de Doña Pepa', 'postre', 420, 4, 70, 14, 100),
  ('Mazamorra Morada', 'postre', 220, 2, 52, 1, 250),
  ('Arroz con Leche', 'postre', 260, 5, 48, 6, 200),
  ('Suspiro a la Limeña', 'postre', 380, 6, 55, 15, 150),
  ('Picarones', 'postre', 350, 5, 60, 11, 150),
  ('King Kong', 'postre', 450, 6, 68, 18, 120),
  ('Chicha Morada', 'bebida', 120, 0, 30, 0, 250),
  ('Inca Kola', 'bebida', 110, 0, 28, 0, 300),
  ('Emoliente', 'bebida', 90, 1, 22, 0, 300),
  ('Quinua Guisada', 'plato de fondo', 320, 12, 50, 8, 300),
  ('Juane de Gallina', 'plato de fondo', 620, 28, 60, 30, 400),
  ('Tacacho con Cecina', 'plato de fondo', 680, 30, 55, 38, 350),
  ('Escabeche de Pescado', 'plato de fondo', 380, 30, 22, 18, 300),
  ('Sudado de Pescado', 'plato de fondo', 320, 32, 15, 14, 350),
  ('Parihuela', 'sopa', 420, 38, 20, 18, 400),
  ('Arroz con Mariscos', 'plato de fondo', 560, 30, 62, 20, 350),
  ('Jalea Mixta', 'plato de fondo', 620, 36, 45, 30, 350),
  ('Chaufa de Mariscos', 'plato de fondo', 600, 28, 68, 24, 350),
  ('Caldo de Gallina', 'sopa', 360, 30, 25, 15, 450),
  ('Adobo Arequipeño', 'plato de fondo', 520, 34, 30, 28, 400),
  ('Chairo Paceño', 'sopa', 400, 20, 45, 14, 400),
  ('Olluquito con Charqui', 'plato de fondo', 380, 22, 40, 14, 300),
  ('Carapulcra', 'plato de fondo', 480, 24, 50, 20, 350),
  ('Frejol Colado', 'postre', 300, 6, 55, 8, 150),
  ('Choclo con Queso', 'entrada', 280, 12, 40, 10, 250),
  ('Empanada de Carne', 'entrada', 320, 12, 32, 16, 150),
  ('Butifarra', 'sandwich', 420, 22, 40, 20, 220),
  ('Leche de Tigre', 'entrada', 140, 18, 10, 3, 200)
;

COMMIT;
